spring.application.name=CarTrackingService

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.mvc.problemdetails.enabled=true

# Docker Compose
spring.docker.compose.file=../compose.yaml


############################
# Metrics / Actuator settings #
############################

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.metrics.export.prometheus.enabled=true

############################
# Logging settings #
############################

logging.file.name=./logs/car-tracking-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_car_tracking
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user_car_tracking
spring.datasource.password=pass_car_tracking
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

# Server
server.port=8085

# Flyway
spring.flyway.enabled=true
spring.flyway.target=latest
spring.flyway.locations=classpath:db/migration

# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

# OAuth2 Client Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/alberioauto
spring.security.oauth2.client.provider.iam-name.issuer-uri=http://localhost:9090/realms/alberioauto
keycloak.clientId=car-tracking-service
keycloak.clientSecret=eeJ8dE7aa4qNLIjAQE1M0M3zWqmUbyPS
keycloak.tokenUri=http://localhost:9090/realms/alberioauto/protocol/openid-connect/token
keycloak.realmUrl=http://localhost:9090/realms/alberioauto