package it.polito.group9.reservationservice.entities

import it.polito.group9.reservationservice.dtos.ReservationDTO
import jakarta.persistence.*

/**
 * Enum class representing the possible statuses of a reservation.
 *
 * @property PENDING The reservation has been created but not yet picked up or with an associated
 *   payment.
 * @property PAID The reservation has been completed, with an associated payment.
 * @property PICKED_UP The reservation has been picked up by the user.
 * @property RETURNED The reservation has been returned by the user.
 * @property CANCELLED The reservation has been cancelled (after refund or no refund needed).
 * @property CANCELLED_PENDING_REFUND The reservation has been cancelled and is waiting for refund
 *   processing.
 */
enum class ReservationStatus {
  PENDING,
  PAID,
  PICKED_UP,
  RETURNED,
  CANCELLED,
  CANCELLED_PENDING_REFUND,
}

/**
 * Entity class representing a reservation in the system.
 *
 * @property id The unique identifier of the reservation, auto-generated by the database.
 * @property vehicle The vehicle associated with the reservation, represented as a one-to-one
 *   relationship.
 * @property userId The ID of the user who made the reservation.
 * @property startDate The start date of the reservation in ISO 8601 format.
 * @property endDate The end date of the reservation in ISO 8601 format.
 */
@Entity
@Table(name = "reservation")
data class Reservation(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null, // Auto-generated primary key
    @ManyToOne
    @JoinColumn(name = "vehicle_id", referencedColumnName = "id")
    val vehicle: Vehicle? = null, // Associated vehicle entity
    val userId: Long, // ID of the user who made the reservation
    @Column(name = "start_date", nullable = false)
    val startDate: String, // Start date of the reservation
    @Column(name = "end_date", nullable = false) val endDate: String, // End date of the reservation
    @Column(name = "status", nullable = false)
    var status: ReservationStatus? = null, // Status of the reservation
    @OneToMany(mappedBy = "reservation", cascade = [CascadeType.ALL], orphanRemoval = true)
    val notes: MutableList<ReservationNote> =
        mutableListOf() // Notes associated with the reservation
) {
  /**
   * Converts this Reservation entity to a ReservationDTO.
   *
   * @return A ReservationDTO containing the data from this Reservation entity.
   * @throws NullPointerException if the `id` or `vehicle` is null.
   */
  fun toDTO(): ReservationDTO {
    return ReservationDTO(
        id = id!!,
        vehicleId = vehicle!!.id!!,
        userId = userId,
        startDate = startDate,
        endDate = endDate,
        status = status,
        vehicleLicensePlate = vehicle!!.licensePlate,
    )
  }
}
