DROP TABLE IF EXISTS api_key;

CREATE TABLE api_key
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    car_id     BIGINT                                  NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_api_key PRIMARY KEY (id)
);

ALTER TABLE api_key
    ADD CONSTRAINT uc_api_key_key UNIQUE (key);
