DROP TABLE IF EXISTS car_location;

CREATE TABLE car_location
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    car_id     BIGINT                                  NOT NULL,
    created_at VARCHAR(255)                            NOT NULL,
    latitude   DOUBLE PRECISION                        NOT NULL,
    longitude  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_car_location PRIMARY KEY (id)
);

CREATE INDEX idx_car_location_car_id ON car_location (car_id);