spring.application.name=PaymentService

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.mvc.problemdetails.enabled=true

# Docker Compose
spring.docker.compose.file=../compose.yaml


############################
# Metrics / Actuator settings #
############################

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always
management.security.enabled=false
management.endpoints.web.base-path=/actuator

############################
# Logging settings #
############################

# Force logback configuration file
logging.config=classpath:logback-spring.xml

# Log file location for Promtail
logging.file.path=./logs
logging.file.name=./logs/payment-service.log

# Log levels
logging.level.it.polito.group9.paymentservice=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.root=INFO

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_payment
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user_payment
spring.datasource.password=pass_payment
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Apache kafka
spring.kafka.producer.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.client-id=payment-service-producer

# Kafka Consumer per ascoltare eventi di reservation
spring.kafka.consumer.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

# Server
server.port=8082

# Flyway
spring.flyway.enabled=true
spring.flyway.target=latest
spring.flyway.locations=classpath:db/migration

# PayPal SDK
paypal.clientId=AWq9JRjo85J1flqiZZAO03foWtnnG9pd5ckA_gRcA2P4sVFvWEUa0e5jHG46ewA9vMvmR7wtI0NW_hWd
paypal.clientSecret=EFChabcLCMT2VCEsbPzR_2d58K5NMxOcjTWLbci8f6XpCQLDO3SuJpK_92mygA3rpY-NPCUnTv63YwAi
paypal.environment=sandbox
paypal.currency=EUR
paypal.returnUrl=http://localhost:8082/api/v1/orders/return
paypal.cancelUrl=http://localhost:8082/api/v1/orders/cancel


# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

# OAuth2 Client Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/alberioauto