DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    surname       VARCHAR(255)                            NOT NULL,
    ssn           VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    phone         VARCHAR(255),
    address       VARCHAR(255),
    date_of_birth date,
    role          VARCHAR(255)                            NOT NULL,
    created_date  date                                    NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_ssn UNIQUE (ssn);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);