CREATE SEQUENCE IF NOT EXISTS car_model_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS maintenance_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS note_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS vehicle_id_seq START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS car_model CASCADE;
DROP TABLE IF EXISTS maintenance CASCADE;
DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;

CREATE TABLE car_model
(
    air_conditioning    BOOLEAN                                 NOT NULL,
    doors               INTEGER                                 NOT NULL,
    luggage             INTEGER                                 NOT NULL,
    motor_displacement  INTEGER                                 NOT NULL,
    price               DOUBLE PRECISION                        NOT NULL,
    seats               INTEGER                                 NOT NULL,
    year                INTEGER                                 NOT NULL,
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand               VARCHAR(255)                            NOT NULL,
    category            VARCHAR(255)                            NOT NULL,
    drivetrain          VARCHAR(255)                            NOT NULL,
    engine_type         VARCHAR(255)                            NOT NULL,
    infotainment_system VARCHAR(255)                            NOT NULL,
    model               VARCHAR(255)                            NOT NULL,
    safety_features     VARCHAR(255)                            NOT NULL,
    segment             VARCHAR(255)                            NOT NULL,
    transmission_type   VARCHAR(255)                            NOT NULL,
    CONSTRAINT car_model_pkey PRIMARY KEY (id)
);

CREATE TABLE maintenance
(
    date                         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upcoming_service_needs       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    vehicle_id                   BIGINT,
    completed_maintenance        VARCHAR(255)                            NOT NULL,
    past_defects                 VARCHAR(255)                            NOT NULL,
    requires_further_cleaning    BOOLEAN                                 NOT NULL,
    requires_further_maintenance BOOLEAN                                 NOT NULL,
    status                       VARCHAR(255)                            NOT NULL,
    CONSTRAINT maintenance_pkey PRIMARY KEY (id)
);

CREATE TABLE note
(
    created_date date                                    NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_id   BIGINT                                  NOT NULL,
    author       VARCHAR(255)                            NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    CONSTRAINT note_pkey PRIMARY KEY (id)
);

CREATE TABLE vehicle
(
    km               INTEGER                                 NOT NULL,
    pending_cleaning BOOLEAN                                 NOT NULL,
    pending_repair   BOOLEAN                                 NOT NULL,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_model_id BIGINT,
    availability     VARCHAR(255)                            NOT NULL,
    license_plate    VARCHAR(255)                            NOT NULL,
    vin              VARCHAR(255)                            NOT NULL,
    CONSTRAINT vehicle_pkey PRIMARY KEY (id)
);

ALTER TABLE car_model
    ADD CONSTRAINT car_model_model_key UNIQUE (model);

ALTER TABLE maintenance
    ADD CONSTRAINT fk1uctvvn1p1y3rp57tq34mao9h FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE NO ACTION;

ALTER TABLE note
    ADD CONSTRAINT fk1cv6ypg7vtv63kwj77p2dnv39 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE NO ACTION;

ALTER TABLE vehicle
    ADD CONSTRAINT vehicle_license_plate_key UNIQUE (license_plate);

ALTER TABLE vehicle
    ADD CONSTRAINT vehicle_vin_key UNIQUE (vin);

ALTER TABLE vehicle
    ADD CONSTRAINT fk5l09vu3ognvllogmsyi1egaj4 FOREIGN KEY (vehicle_model_id) REFERENCES car_model (id) ON DELETE NO ACTION;
