DROP TABLE IF EXISTS reservation CASCADE;

CREATE TABLE reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_id BIGINT,
    user_id    BIGINT                                  NOT NULL,
    start_date VARCHAR(255)                            NOT NULL,
    end_date   VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);