spring.application.name=UserManagementService

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.mvc.problemdetails.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/db_usermanagement
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user_usermanagement
spring.datasource.password=pass_usermanagement
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.file=../compose.yaml

server.port=8081

############################
# Metrics / Actuator settings #
############################

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always
management.security.enabled=false
management.endpoints.web.base-path=/actuator

############################
# Logging settings #
############################

# Force logback configuration file
logging.config=classpath:logback-spring.xml

# Log file location for Promtail
logging.file.path=./logs
logging.file.name=./logs/user-management-service.log

# Log levels
logging.level.it.polito.group9.usermanagementservice=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.root=INFO

# Flyway
spring.flyway.enabled=true
spring.flyway.target=latest
spring.flyway.locations=classpath:db/migration

# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

# OAuth2 Client Configuration
spring.security.oauth2.client.provider.iam-name.issuer-uri=http://localhost:9090/realms/alberioauto

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/alberioauto

keycloak.client-id=user-management-service
keycloak.client-secret=Eu0pMivZbYU6L3XBIuyB3y8S8wGY7v30
keycloak.realm-url=http://localhost:9090/realms/alberioauto
keycloak.token-uri=http://localhost:9090/realms/alberioauto/protocol/openid-connect/token
keycloak.realm=alberioauto
keycloak.auth-server-url=http://localhost:9090
